// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {config} from '../models';

export function Close():Promise<void>;

export function CreateSession(arg1:app.CreateOptions):Promise<app.SessionInfo>;

export function GetConfig():Promise<config.Config>;

export function GetWebSocketPort():Promise<number>;

export function LoadSessions():Promise<Array<app.SessionInfo>>;
