// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['app']['SessionAPI']['Close']();
}

export function CreateSession(arg1) {
  return window['go']['app']['SessionAPI']['CreateSession'](arg1);
}

export function GetConfig() {
  return window['go']['app']['SessionAPI']['GetConfig']();
}

export function GetWebSocketPort() {
  return window['go']['app']['SessionAPI']['GetWebSocketPort']();
}

export function LoadSessions() {
  return window['go']['app']['SessionAPI']['LoadSessions']();
}
